import Header from '@/components/Header/Header';
import '@fortawesome/fontawesome-svg-core/styles.css';
import './globals.scss';
import { roboto, montserrat } from '../../fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
